// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyasmnsbddufkyhcdroj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5YXNtbnNiZGR1Zmt5aGNkcm9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODU4NTksImV4cCI6MjA3MjU2MTg1OX0.Fp_TAe3eZjSBvIINLo_M62JFnp-18v15Ezxho121dHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});